#!/bin/bash -e
#                                                -*-shell-script-*-
#
# Build Docker container images based on settings derived from
# $IMAGE_NAME, etc.
#
# https://docs.docker.com/docker-hub/builds/advanced/

exec ./build.sh $IMAGE_NAME
